# -*- coding: utf-8 -*-
"""task1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SGcARNYe9hkemRS3sX8WFffvIf2nLk8d
"""

#task1a

def func(N, S, arr):
    idx = {}
    for i in range(N):
        for j in range(i+1, N):
            if arr[i] + arr[j] == S:
                return i+1, j+1
    return "IMPOSSIBLE"

with open('input1a.txt', 'r') as file:
    N, S = map(int, file.readline().split())
    arr = list(map(int, file.readline().split()))

with open('output1a.txt', 'w') as file:
    idx = func(N, S, arr)
    if idx == "IMPOSSIBLE":
        file.write("IMPOSSIBLE")
    else:
        file.write(f"{idx[0]} {idx[1]}")