# -*- coding: utf-8 -*-
"""task1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SGcARNYe9hkemRS3sX8WFffvIf2nLk8d
"""

#task1b

def func(N, S, nums):
    dic = {}
    for i in range(N):
        x = S - nums[i]
        if x in dic:
            return dic[x], i+1
        dic[nums[i]] = i+1
    return "IMPOSSIBLE"

with open("input1b.txt", "r") as file:
    N, S = map(int, file.readline().split())
    nums = list(map(int, file.readline().split()))

idx = func(N, S, nums)

with open("output1b.txt", "w") as file:
    if idx == "IMPOSSIBLE":
        file.write("IMPOSSIBLE")
    else:
        file.write(f"{idx[0]} {idx[1]}")