# -*- coding: utf-8 -*-
"""Task_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxccN8chq9hfliXXjxP2mWXBpvwt5yfz
"""

#Task2:

input_file = open("input2.txt")
output_file = open("output2.txt", "w")
s = input_file.readline()
sl = s.split(" ")
sl1 = []
for i in sl:
    sl1.append(int(i))
print(sl1)
####################################################
def Fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)

n = sl1[0]
print(Fibonacci(n+1))
########################################################
input_file.close()
output_file.close()