# -*- coding: utf-8 -*-
"""Task_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxccN8chq9hfliXXjxP2mWXBpvwt5yfz
"""

#Task1:

input_file = open("input1.txt")
output_file = open("output1.txt", "w")
s = input_file.readline()
sl = s.split(" ")
sl1 = []
for i in sl:
    sl1.append(int(i))
print(sl1)
list1=[]
################################################
for i in range(sl1[1]):
    ss = input_file.readline()
    ssl = ss.split(" ")
    ssl1 = []
    for j in ssl:
        ssl1.append(int(j))
    list1.append(ssl1)
print(list1)
####################################################
def bubbleSort(array):
  for i in range(len(array)):
    for j in range(0, len(array) - i - 1):
      if array[j][2] > array[j + 1][2]:
        temp = array[j]
        array[j] = array[j+1]
        array[j+1] = temp
bubbleSort(list1)
print(list1)
print()
##########################################
list2 = []
for i in list1:
    if i[0] not in list2:
        list2.append(i[0])
    if i[1] not in list2:
        list2.append(i[1])
list2.sort()
print(list2)
list22 = []
for i in list2:
    temp = []
    temp.append(i)
    list22.append(temp)
print(list22)
print()
##############################################
list3 = []
for i in list1:
    c = 0
    for j in list22:
        if i[0] in j and i[1] in j:
            c = 1
            break
        else:
            c = 0
    if c == 0:
        ind1 = 0
        ind2 = 0
        for k in range(len(list22)):
            if i[0] in list22[k]:
                ind1 = k
            if i[1] in list22[k]:
                ind2 = k
        list22[ind1].extend(list22[ind2])
        list22.pop(ind2)
        list3.append(i[2])

print(list22)
print(list3)
s = 0
for i in list3:
    s += i
print(s)
print(s,file=output_file)
########################################################
input_file.close()
output_file.close()