# -*- coding: utf-8 -*-
"""Task_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxccN8chq9hfliXXjxP2mWXBpvwt5yfz
"""

#Task3:

input_file = open("input3.txt")
output_file = open("output3.txt", "w")
s = input_file.readline()
print(sl)
sl1 = []
for i in range(len(sl)-1):
    sl1.append(int(sl[i]))
print(sl1)
list1=[]
################################################
for i in range(1):
    ss = input_file.readline()
    ssl = ss.split(" ")
    ssl1 = []
    for j in ssl:
        ssl1.append(int(j))
print(ssl1)
####################################################
def bubbleSort(array):
  for i in range(len(array)):
    for j in range(0, len(array) - i - 1):
      if array[j] < array[j + 1]:
        temp = array[j]
        array[j] = array[j+1]
        array[j+1] = temp
bubbleSort(ssl1)
print(ssl1)
print()
########################################################
c = 0
sum = sl1[1]
for i in range(len(ssl1)):
    if ssl1[i] != ssl1[-1]:
        while True:
            t = sum - ssl1[i]
            if t >= ssl1[-1]:
                sum = t
                c += 1
            else:
                break
    else:
        while True:
            sum = sum - ssl1[i]
            c += 1
            if sum == 0:
                break

print(c)
print(c,file=output_file)
#########################################################
input_file.close()
output_file.close()